name: QuizNose

on:
  push:
    branches: [main]
    # workflow_dispatch allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Official GitHub Action used to check-out a repository so a workflow can access it
        uses: actions/checkout@v2

      - name: Building the Flask Application and serving it in background
        run: |
          docker build -t quiznose-app -f docker/Dockerfile .
          docker run -d --rm -p 8080:5000 quiznose-app

      - name: Install Cypress Dependencies
        run: |
          cd cypress
          npm install

      - name: Executing Cypress Test using official Cypress GitHub Action.
        uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:8080"
          browser: firefox
          spec: ./cypress/integration/test.spec.js
          working-directory: ./cypress

  provision_aws_resources:
    needs: build_and_test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Official GitHub Action used to check-out a repository so a workflow can access it
        uses: actions/checkout@v2

      - name: Offical Terraform action which uses a JavaScript action that sets up Terraform CLI in your GitHub Actions workflow
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_REGION: us-east-1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform format, initialize, plan, and apply resources
        run: |
          cd terraform
          terraform fmt -recursive
          terraform init
          terraform plan
          terraform apply -auto-approve

  push_to_ecr:
    needs: provision_aws_resources
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Official GitHub Action used to check-out a repository so a workflow can access it
        uses: actions/checkout@v2

      - name: Provides a mechanism to configure AWS credential and region environment variables for use in other GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_REGION: us-east-1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Logs into Amazon ECR with the local Docker client.
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push successful image to ECR with specific environment variables.
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
